
CREATE SCHEMA `cultos` ;

USE cultos;



CREATE TABLE Horario (
  idHorario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  horario VARCHAR(20) NULL, 
  Quantidade INTEGER UNSIGNED NULL,
  PRIMARY KEY(idHorario)
) AUTO_INCREMENT = 1;
-- DROP TABLE Usuario
CREATE TABLE Usuario (
  IdUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NomeCompleto VARCHAR(500) NOT NULL,
  Telefone VARCHAR(20) NOT NULL,
  IND_ATIVO INTEGER NOT NULL,
  PRIMARY KEY(IdUsuario)
) AUTO_INCREMENT = 1;

-- DROP TABLE USUARIO_HORARIO
CREATE TABLE USUARIO_HORARIO (
IdUsuario INT UNSIGNED NOT NULL,
idHorario INT UNSIGNED NOT NULL,
FOREIGN KEY (IdUsuario) REFERENCES Usuario (IdUsuario),
FOREIGN KEY (idHorario) REFERENCES Horario (idHorario)
);


INSERT INTO Horario (horario, Quantidade)  VALUES('8:30 às 12:00', 30);



--UPDATE Horario SET QUANTIDADE = 0 WHERE idHorario = 1

select idHorario, horario, Quantidade from Horario


SELECT * FROM USUARIO_HORARIO
SELECT A.IDUSUARIO,  A.NOMECOMPLETO, A.TELEFONE FROM USUARIO A
INNER JOIN USUARIO_HORARIO B ON A.IDUSUARIO = B.IDUSUARIO
INNER JOIN HORARIO C ON C.IDHORARIO = B.IDHORARIO
ORDER BY C.IDHORARIO 


ALTER TABLE USUARIO ADD COLUMN TELEFONE varchar(30);

select * from horario

SELECT * FROM USUARIO



SELECT A.IDUSUARIO, A.NOMECOMPLETO, A.TELEFONE, C.HORARIO, C.IDHORARIO, A.IND_ATIVO FROM USUARIO A
                                            INNER JOIN USUARIO_HORARIO B ON A.IDUSUARIO = B.IDUSUARIO
                                            INNER JOIN HORARIO C ON C.IDHORARIO = B.IDHORARIO
									WHERE A.IND_ATIVO = 1
                                            ORDER BY C.IDHORARIO



update USUARIO set IND_ATIVO = 1 where idusuario = 17

  




